name: "Cleanup Workspace"
description: "Deletes all files in the work directory."
runs:
  using: "docker"
  image: "docker://m8ns.sparsetechnology.com:5050/sparse/images/action-cleanup:latest"
  post-entrypoint: /entrypoint.sh
branding:
  icon: delete
  color: red
